# Generated by Django 5.0.6 on 2024-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('custo_inicial', models.FloatField()),
                ('depreciacao_anual', models.FloatField()),
                ('expectativa_vida_util', models.IntegerField()),
            ],
        ),
    ]
