# Generated by Django 5.0.6 on 2024-06-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_edificio_equipamento_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='data_aquisicao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='depreciacao_anual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='expectativa_vida_util',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='depreciacao_anual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='expectativa_vida_util',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='data_aquisicao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='depreciacao_anual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='expectativa_vida_util',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_aquisicao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='depreciacao_anual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='expectativa_vida_util',
            field=models.IntegerField(default=0.0),
        ),
    ]
