# Generated by Django 5.0.6 on 2024-07-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_alter_edificio_data_aquisicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='depreciacao_anual',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='expectativa_vida_util',
            field=models.IntegerField(default=25.0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='depreciacao_anual',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='expectativa_vida_util',
            field=models.IntegerField(default=10.0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='depreciacao_anual',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='expectativa_vida_util',
            field=models.IntegerField(default=10.0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='depreciacao_anual',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='expectativa_vida_util',
            field=models.IntegerField(default=5.0),
        ),
    ]
