# Generated by Django 5.0.6 on 2024-07-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_alter_edificio_depreciacao_anual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='depreciacao_anual',
            field=models.FloatField(verbose_name=20.0),
        ),
    ]
