# Generated by Django 5.0.6 on 2024-07-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0005_alter_veiculo_depreciacao_anual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='depreciacao_anual',
            field=models.FloatField(default=20.0),
        ),
    ]
